spring:
  profiles: aws

server:
  port: 0

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://ip-172-31-26-103.eu-central-1.compute.internal:8761/eureka/