spring:
  profiles: aws

server:
  port: 0

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://ec2-52-58-87-195.eu-central-1.compute.amazonaws.com:8761/eureka/

app:
  aws:
    init:
      instance:
        duration: 90000
        max: 5
    securityGroup: sg-5f2cd437
    services:
      checkstyle:
        imageId: ami-7fbe5710
        instanceType: t2.micro
        keyName: aws_frankfurt
      pmd:
        imageId: ami-c452bbab
        instanceType: t2.micro
        keyName: aws_frankfurt
